import 'bootstrap/dist/css/bootstrap.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import Script from 'next/script';
import BootstrapClient from './../components/bootstrapClient';
import Navbar from '../components/ui/navbar';
import Footer from '../components/ui/footer';
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Script src="/js/main.js" strategy="afterInteractive" />

        {/* Navbar */}
        <Navbar />

        {/* Main Content with padding to prevent overlap */}
        <main style={{ paddingTop: "80px" }}>
          {children}
        </main>

        {/* Footer inside BootstrapClient */}
        <BootstrapClient>
          <Footer />
        </BootstrapClient>
      </body>
    </html>
  );
}
